### **Student Information**
Name: 鄭振慈 Patrick Thelysander

Student ID: 61347113S

GitHub ID: Osiris181

Kaggle name: Patrick Thelysander

Kaggle private scoreboard snapshot: 

Kaggle public scoreboard snapshot:

![pic_ranking.png](./pics/public_leaderboard_kaggle.png)

---

# **Instructions**

For this lab we have divided the assignments into **three phases/parts**. The `first two phases` refer to the `exercises inside the Master notebooks` of the [DM2025-Lab2-Exercise Repo](https://github.com/difersalest/DM2025-Lab2-Exercise.git). The `third phase` refers to an `internal Kaggle competition` that we are gonna run among all the Data Mining students. Together they add up to `100 points` of your grade. There are also some `bonus points` to be gained if you complete `extra exercises` in the lab **(bonus 15 pts)** and in the `Kaggle Competition report` **(bonus 5 pts)**.

**Environment recommendations to solve lab 2:**
- **Phase 1 exercises:** Need GPU for training the models explained in that part, if you don't have a GPU in your laptop it is recommended to run in Colab or Kaggle for a faster experience, although with CPU they can still be solved but with a slower execution.
- **Phase 2 exercises:** We use Gemini's API so everything can be run with only CPU without a problem.
- **Phase 3 exercises:** For the competition you will probably need GPU to train your models, so it is recommended to use Colab or Kaggle if you don't have a laptop with a dedicated GPU.
- **Optional Ollama Notebook (not graded):** You need GPU, at least 4GB of VRAM with 16 GB of RAM to run the local open-source LLM models. 

## **Phase 1 (30 pts):**

1. __Main Exercises (25 pts):__ Do the **take home exercises** from Sections: `1. Data Preparation` to `9. High-dimension Visualization: t-SNE and UMAP`, in the [DM2025-Lab2-Master-Phase_1 Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_1.ipynb). Total: `8 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 3th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

## **Phase 2 (30 pts):**

1. **Main Exercises (25 pts):** Do the remaining **take home exercises** from Section: `2. Large Language Models (LLMs)` in the [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb). Total: `5 exercises required from sections 2.1, 2.2, 2.4 and 2.6`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

2. **Code Comments (5 pts):** **Tidy up the code in your notebook**. 

3. **`Bonus (15 pts):`** Complete the bonus exercises in the [DM2025-Lab2-Master-Phase_2_Bonus Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Bonus.ipynb) and [DM2025-Lab2-Master-Phase_2_Main Notebook](https://github.com/difersalest/DM2025-Lab2-Exercise/blob/main/DM2025-Lab2-Master-Phase_2_Main.ipynb) `where 2 exercises are counted as bonus from sections 2.3 and 2.5 in the main notebook`. Total: `7 exercises`. Commit your code and submit the repository link to NTU Cool **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**

## **Phase 3 (40 pts):**

1. **Kaggle Competition Participation (30 pts):** Participate in the in-class **Kaggle Competition** regarding Emotion Recognition on Twitter by clicking in this link: **[Data Mining Class Kaggle Competition](https://www.kaggle.com/t/3a2df4c6d6b4417e8bf718ed648d7554)**. The scoring will be given according to your place in the Private Leaderboard ranking: 
    - **Bottom 40%**: Get 20 pts of the 30 pts in this competition participation part.

    - **Top 41% - 100%**: Get (0.6N + 1 - x) / (0.6N) * 10 + 20 points, where N is the total number of participants, and x is your rank. (ie. If there are 100 participants and you rank 3rd your score will be (0.6 * 100 + 1 - 3) / (0.6 * 100) * 10 + 20 = 29.67% out of 30%.)   
    Submit your last submission **`BEFORE the deadline (Nov. 24th, 11:59 pm, Monday)`**. Make sure to take a screenshot of your position at the end of the competition and store it as `pic_ranking.png` under the `pics` folder of this repository and rerun the cell **Student Information**.

2. **Competition Report (10 pts)** A report section to be filled in inside this notebook in Markdown Format, we already provided you with the template below. You need to describe your work developing the model for the competition. The report should include a section describing briefly the following elements: 
* Your preprocessing steps.
* The feature engineering steps.
* Explanation of your model.

* **`Bonus (5 pts):`**
    * You will have to describe more detail in the previous steps.
    * Mention different things you tried.
    * Mention insights you gained. 

[Markdown Guide - Basic Syntax](https://www.markdownguide.org/basic-syntax/)

**`Things to note for Phase 3:`**

* **The code used for the competition should be in this Jupyter Notebook File** `DM2025-Lab2-Homework.ipynb`.

* **Push the code used for the competition to your repository**.

* **The code should have a clear separation for the same sections of the report, preprocessing, feature engineering and model explanation. Briefly comment your code for easier understanding, we provide a template at the end of this notebook.**

* Showing the kaggle screenshot of the ranking plus the code in this notebook will ensure the validity of your participation and the report to obtain the corresponding points.

After the competition ends you will have two days more to submit the `DM2025-Lab2-Homework.ipynb` with your report in markdown format and your code. Do everything **`BEFORE the deadline (Nov. 26th, 11:59 pm, Wednesday) to obtain 100% of the available points.`**

Upload your files to your repository then submit the link to it on the corresponding NTU Cool assignment.

## **Deadlines:**

![lab2_deadlines](./pics/lab2_deadlines.png)

---

Next you will find the template report with some simple markdown syntax explanations, use it to structure your content.

You can delete the syntax suggestions after you use them.

---

***

# **Project Report**

**Syntax:** `#` creates the largest heading (H1).

---
**Syntax:** `---` creates a horizontal rule (a separator line).

## 1. Model Development (10 pts Required)

**Syntax:** `##` creates a secondary heading (H2).

**Describe briefly each section, you can add graphs/charts to support your explanations.**

### 1.1 Preprocessing Steps

**Syntax:** `###` creates a tertiary heading (H3).

[Content for Preprocessing]

**Example Syntax for Content:**
*   **Bold text:** `**text**`
*   *Italic text*: `*text*`
*   Bullet point list:
    * Item 1
    * Item 2

Markdown Syntax to Add Image: `![Description of the Image](./your_local_folder/name_of_the_image.png)`

![Example Markdown Syntax to Add Image](./pics/example_md_img.png)

### 1.2 Feature Engineering Steps

[Content for Feature Engineering]

### 1.3 Explanation of Your Model

[Content for Model Explanation]

---

## 2. Bonus Section (5 pts Optional)

**Add more detail in previous sections**

### 2.1 Mention Different Things You Tried

[Content for Experiments]

### 2.2 Mention Insights You Gained

[Content for Insights]

---

**`From here on starts the code section for the competition.`**

---

# **Competition Code + Report**
I combined the code and report so that the explanation would be correlated with the code parts
## 1. Preprocessing Steps

### All required Imports

In [ ]:
import json
import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, AutoModelForSequenceClassification, DataCollatorWithPadding, Trainer
import numpy as np
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

### Load the data from JSON and store it into Panda

In [ ]:
### Add the code related to the preprocessing steps in cells inside this section
with open("./dm-lab-2-private-competition/final_posts.json", "r", encoding="utf-8") as f: #specify encoding to prevent error
    content_extracted_raw = json.load(f)
content_extracted_raw

[{'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x61fc95',
     'text': 'We got the ranch, loaded our guns and sat up till sunrise.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x35663e',
     'text': 'I bet there is an army of married couples who did the same exact thing.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc78afe',
     'text': 'This could only end badly.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x90089c',
     'text': 'My sister squeezed a lime in her milk when she was 12. Same thing happened, but we told her it would happen AFTER she did it ..',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xaba820',
     'text': 'and that got my head bobbing a little bit.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x66e44d',
     'text': "Same. Glad it's not just out store.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc03cf5',
     'text': 'Like always i will wait and see thanks for the post tho [NAME]',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x2ffb63',
     'text': 'Thank you so much❤️',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x02f65a',
     'text': 'There\'s a bit of room between "not loving sub-zero temperatures" and "never going outside."',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x989146',
     'text': 'Stinks because ive been in this program for a year with no pay.....back to the drawing board.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x111ebf',
     'text': 'The overall response is try and empower women, abolish prostitution and stop giving lazy men money because they want to live out their idiotic fantasy lives. ',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb9a96c',
     'text': 'Your market sucks',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xcc5e81',
     'text': 'here’s hoping the same is true for me!',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x08f6d6',
     'text': 'She looks like a televangelist.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb855e1',
     'text': "Rap that will Cut other raper's throat. Who said that? @Paedeezy #badd #wicked. #bright city lights",
     'hashtags': ['badd', 'wicked', 'bright']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xaa3a20',
     'text': 'She’s a good person who stands up for people not like her, and they can’t stand that.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x479407',
     'text': 'Okay I can see this looking really cool for a festival or photos though 😄',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x784799',
     'text': 'I do but I like my job. I just hate the fact I HAVE to go do it.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xd64e57',
     'text': 'What were they mumbling at the end before the commercial break? That was weird.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x77f7de',
     'text': 'I wanna go to fright fest with squad',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xe07a21',
     'text': 'I screamed the chest pain was so bad i clutched my chest.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x0efb36',
     'text': 'Everything I order online just comes looking like a piece of shit 😤',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xd97dc1',
     'text': 'Thanks <3',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5bbbaf',
     'text': 'holy lmao im a dolt lol.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x0f6fe1',
     'text': "@lefluerr Lol yeah I read that but I stayed up and didn't nap tillI collect 3 people who I think they've got me 😂😂!!",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x63778f',
     'text': "I don't get your point. I love the grind as well, that's why I tried to get dark matter and prestige master. ",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5ab56d',
     'text': 'Dear [NAME], please help [NAME] be less disgusting. Amen.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x06d186',
     'text': 'Fuck I love you prag',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc17678',
     'text': 'LIIIIIIIIIII🅱IIIIIIIIIIIIT. fat bastard was on sunday that i’m too lazy to crop the photo.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa9a658',
     'text': 'After this, I understand why outside Guangdong, all efforts go unrewarded — and you still get blamed when something happens.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x608869',
     'text': 'Why did it fracture from just a kick?',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa41842',
     'text': 'maybe you learned it from the yellow vest movement in France?',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x6b3627',
     'text': 'This is where the story gets CREEPY.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xf2c061',
     'text': 'My god, what is WRONG with people? So glad you’re okay, OP!!',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa0d2b5',
     'text': 'I love the way he looks at them to see if he should keep panting.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa8a536',
     'text': 'Wow he is very gifted! I hope he continues to freeze more buffalos!',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xf6092f',
     'text': '“Talent determines your speed; effort determines your height and endurance.” — Work hard, harder, hardest.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc39185',
     'text': 'Poor critter D:',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa2e767',
     'text': "Huh, so there should be no more men's and women's sports, bathrooms, prisons, etc.?",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xdcb12d',
     'text': "Except... that's exactly what I was taught in [RELIGION] school. One god, theee aspects.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x7d8c89',
     'text': 'I know this might be an unpopular opinion from reading this post but I have a gut feeling that [NAME] and [NAME] would pair up really well together.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x0a0102',
     'text': 'Having a baby born too soon is #lifechanging 6 years on and it feels like only yesterday #sad #happy  #emotionalrollercoaster',
     'hashtags': ['lifechanging',
      'sad',
      'happy',
      'emotionalrollercoaster']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xebf370',
     'text': "You didn't need to split this into two posts...",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5a52b9',
     'text': 'Feels like no one’s spared. Chinese public may lack expertise, but at least they don’t drink disinfectant like Americans.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x583ce2',
     'text': "Exactly! The mob mentality of these people is sad! Let's bring some love and peace into the world!",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x54afc3',
     'text': 'Liberal circlejerk “ o ya those conservatives suck” 10,000 upvotes',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa794c1',
     'text': 'HEY BEAUTIES ITS ME SASHA VELOUR',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc32edf',
     'text': '>Rise of Agon Literally the worst fucking game that man kind has ever managed to accomplish and you call him a carebear? Fuck out of here.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x787ff9',
     'text': 'You conveniently ignored my response to this naivety when you said it before.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x198b91',
     'text': "To bad trophy wife doesn't have 4th place.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x05ff68',
     'text': 'Me too! I was thinking about this yesterday.... I want to be in love again.😕',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x3931ad',
     'text': 'My least favorite couple: [NAME] and [NAME].',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc81672',
     'text': '“May he never get hurt cycling, no swollen knees, no muscle strain; may he always be safe, joyful, and smooth on his cycling journey.”',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x17646e',
     'text': 'I don’t know how to write odds for an event as certain as that.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x145c99',
     'text': 'The 5 days got an audible "[NAME]" out of me. That\'s terrifying. ',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x745c66',
     'text': '@ananavarro @tcarrels most of Trump supporters have not clue about the meaning of the words they used just like him #sad #nevertrump',
     'hashtags': ['sad', 'nevertrump']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x3ed9e0',
     'text': 'digitally executed lol.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa413f7',
     'text': 'Hey man skol vikings. Support however you’d like, just as long as you support ',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x6c2c68',
     'text': 'Thanks, i have to wake up early tomorrow ish.. i cant now but if i think of any other questions i will, ❤',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5025d6',
     'text': 'What a joke',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb41434',
     'text': '@ananavarro @tcarrels most of Trump supporters have not clue about the meaning of the words they used just like him  #nevertrump',
     'hashtags': ['nevertrump']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x75fc2c',
     'text': 'Tomorrow is the day I cut and dye my hair! 😳 #nervous #excited',
     'hashtags': ['nervous', 'excited']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xab20d5',
     'text': 'Probably because he is in a spiderman suit and is planning on doing something funny.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x4cfc30',
     'text': "@CarrieLynne2323 totally get it. When you've said no to donuts 13 times one week and lost 0.3 lbs you get discouraged! But it's not linear 😘",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xc4a501',
     'text': "Organs are literal superfoods and it weirds me out there hasn't been some fad diet with them yet.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x82e70d',
     'text': '@TweeriaLee A stumbling block to the pessimist is a stepping stone to the optimist.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xda3368',
     'text': 'The fact that you got a kill with the auger is impressive enough...here’s an upvote',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x48b7ea',
     'text': "@StrangeFacesLA why doesn't this account follow me #offended",
     'hashtags': ['offended']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb25068',
     'text': 'Kayaking is merriment together with sevylor inflatable kayaks: eYGgJxMl',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xbc0fef',
     'text': 'Would you give your used underwear to your best friend/romantic interest? >!I know I have.!<',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5fd03b',
     'text': "I'm flying home to stl tonight. Land at 8pm. Have to get all the way down 44.....fuck.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb3c4d5',
     'text': 'Tough scene for [NAME]',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5907df',
     'text': "bout to read this article 'Moving the Conversation Forward: Homosexuality &amp; Christianity' from someone in the foursquare church ",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xa6d431',
     'text': "I was always in awe of just how stunning she was. She doesn't photograph well though, it's a shame. ",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x16d325',
     'text': 'I often do this when I listen to metal. It helps vent some of the anger I feel.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xdcf537',
     'text': 'How to handle incubation periods? You can still test positive after quarantine. Multiple tests aren’t helpful. Be lenient and people scold; lose control and get blamed — what choice do officials have?',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xedee99',
     'text': "Yeah I just saw that. The wheels are turnin' :)",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x745344',
     'text': "It doesn't look like it.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x574ebe',
     'text': 'The arch is so cool. I love St Louis',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x63305f',
     'text': 'This hit me a little too close to home',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xb9201b',
     'text': 'I think you two are obligated to go to bed together now.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5f0242',
     'text': 'Ooh, the pupil proportion was wonderful at this time.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x5ec84b',
     'text': "Yikes. I was kind of excited to get a new [NAME] if he gets last man in but I'll pass on these butt ugly jerseys.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x44c4cc',
     'text': 'Thank you sir, this has made me happy. ',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x358594',
     'text': 'I try to keep my hands busy. I would do better when I have acrylic nails because it wasn’t as easy/just wasn’t the same.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xf4e662',
     'text': '@BoJackHorseman if your depressed and somebody calls you long faced will you still automatically take umbrage?',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x925dae',
     'text': 'He was shrieking at everything up until then. Like I said I was worried in the beginning but sometimes it works out.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x7b3a81',
     'text': '*sobbing* I love you bro, you always there for me *continues sobbing*',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xe1add2',
     'text': 'Good for you. But ignoring [NAME] situation makes the article pointless.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x4bd129',
     'text': 'Then again but harder.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x99e889',
     'text': 'I keep getting my posts removed and banned from that sub. 😒',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xbdf2c5',
     'text': "Wow, didn't expect this thread to get philosophical.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x11449a',
     'text': '> their personal choices and clothing are distinct from their legislation and policies. This has got to be a fucking joke. What universe do you live in?',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x749b94',
     'text': "I know I've painted quite a grim picture of your chances. But if you simply stand here, we will both surely die.",
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x001058',
     'text': 'I was having a #BadDay and i went on #YouTube and watched @domoandcrissy reaction to old pics. #Thanks #ladies for the #laughs',
     'hashtags': ['badday', 'youtube', 'thanks', 'ladies', 'laughs']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x894c0a',
     'text': 'I closed my eyes and took a deep breath.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x76061e',
     'text': 'That entire family is so embarrassing.',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xe1b416',
     'text': 'Slap her hand if she is trying to force you to do anything! Tell her not to put her hands on you, and enforce it every time. ',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xedd663',
     'text': 'OMG... Dad!',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xe0fe3b',
     'text': "It's always over.. until I'm no longer sober... then it feels like I wana start over #UL",
     'hashtags': ['ul']}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x6c7be0',
     'text': 'What a dumbass question to start with...',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x892047',
     'text': 'Bop employee here. Not GLAD',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0xf176ac',
     'text': 'As long as the stop watch on my iPhone is timing him, my kid will do almost any chore. Its crazy what kids find exciting',
     'hashtags': []}}}},
 {'root': {'_type': 'post',
   '_source': {'post': {'post_id': '0x74870b',

In [ ]:
# open the JSON file and put it into pandas dataframe
file_path = './dm-lab-2-private-competition/final_posts.json'

with open(file_path, 'r', encoding="utf-8") as f:
    data = json.load(f)

if isinstance(data, dict):
    input_data = [data]
else:
    input_data = data

df_normalize = pd.json_normalize(input_data, sep='_') 
df_normalize = df_normalize.rename(columns={'root__source_post_post_id': 'id'})
df_normalize

,root__type,id,root__source_post_text,root__source_post_hashtags
0,post,0x61fc95,"We got the ranch, loaded our guns and sat up t...",[]
1,post,0x35663e,I bet there is an army of married couples who ...,[]
2,post,0xc78afe,This could only end badly.,[]
3,post,0x90089c,My sister squeezed a lime in her milk when she...,[]
4,post,0xaba820,and that got my head bobbing a little bit.,[]
...,...,...,...,...
64166,post,0x4afbe1,Guilty Gear actually did that before with Guil...,[]
64167,post,0xf5ba78,One of my favorite episodes.,[]
64168,post,0x8f758e,I got my first raspberry from a crowd surfer f...,[]
64169,post,0xb5a35a,Texans and Astros both shut out tonight. Houst...,"[texans, astros, sadness, losers]"
64170,post,0x3a9174,Pre-prepare direction plays hale and hearty si...,[]

In [ ]:
# read the data identificaation to make the train and test dataframe
df_dataId = pd.read_csv("./dm-lab-2-private-competition/data_identification.csv")
df_dataId

             id  split
0      0x61fc95   test
1      0x35663e  train
2      0xc78afe  train
3      0x90089c  train
4      0xaba820   test
...         ...    ...
64166  0x4afbe1  train
64167  0xf5ba78  train
64168  0x8f758e   test
64169  0xb5a35a  train
64170  0x3a9174   test

[64171 rows x 2 columns]

In [ ]:
# load the groundtruth
df_emotion = pd.read_csv("./dm-lab-2-private-competition/emotion.csv")
df_emotion

             id  emotion
0      0x35663e      joy
1      0xc78afe     fear
2      0x90089c      joy
3      0x2ffb63      joy
4      0x989146      joy
...         ...      ...
47885  0xd740f2      joy
47886  0x99267e    anger
47887  0x4afbe1    anger
47888  0xf5ba78      joy
47889  0xb5a35a  sadness

[47890 rows x 2 columns]

In [ ]:
# get all of the ID of the train dataset
train = df_dataId[df_dataId['split'] == 'train']
train

             id  split
1      0x35663e  train
2      0xc78afe  train
3      0x90089c  train
7      0x2ffb63  train
9      0x989146  train
...         ...    ...
64164  0xd740f2  train
64165  0x99267e  train
64166  0x4afbe1  train
64167  0xf5ba78  train
64169  0xb5a35a  train

[47890 rows x 2 columns]

In [ ]:
# get all of the ID of the test dataset
test = df_dataId[df_dataId['split'] == 'test']
test

             id split
0      0x61fc95  test
4      0xaba820  test
5      0x66e44d  test
6      0xc03cf5  test
8      0x02f65a  test
...         ...   ...
64146  0x0f273c  test
64150  0xfc4c5d  test
64157  0xb318a3  test
64168  0x8f758e  test
64170  0x3a9174  test

[16281 rows x 2 columns]

In [ ]:
# merge the groundtruth to the training dataset
df_train = pd.merge(df_normalize, train, "inner", "id")
df_train_final = pd.merge(df_train, df_emotion, "inner", "id")
df_train_final = df_train_final.reset_index(drop=True)
# df_train_final.to_csv("train.csv")
df_train_final

,root__type,id,root__source_post_text,root__source_post_hashtags,split,emotion
0,post,0x35663e,I bet there is an army of married couples who ...,[],train,joy
1,post,0xc78afe,This could only end badly.,[],train,fear
2,post,0x90089c,My sister squeezed a lime in her milk when she...,[],train,joy
3,post,0x2ffb63,Thank you so much❤️,[],train,joy
4,post,0x989146,Stinks because ive been in this program for a ...,[],train,joy
...,...,...,...,...,...,...
47885,post,0xd740f2,why is everybody seem sp serious?,[],train,joy
47886,post,0x99267e,"You can cross fuck off, its 10f all winter in ...",[],train,anger
47887,post,0x4afbe1,Guilty Gear actually did that before with Guil...,[],train,anger
47888,post,0xf5ba78,One of my favorite episodes.,[],train,joy
47889,post,0xb5a35a,Texans and Astros both shut out tonight. Houst...,"[texans, astros, sadness, losers]",train,sadness

In [ ]:
# merge the test dataset (dataset that is going to be used for the predictions)
df_test = pd.merge(df_normalize, test, "inner", "id")
df_test = df_test.reset_index(drop=True)

df_test

,root__type,id,root__source_post_text,root__source_post_hashtags,split
0,post,0x61fc95,"We got the ranch, loaded our guns and sat up t...",[],test
1,post,0xaba820,and that got my head bobbing a little bit.,[],test
2,post,0x66e44d,Same. Glad it's not just out store.,[],test
3,post,0xc03cf5,Like always i will wait and see thanks for the...,[],test
4,post,0x02f65a,"There's a bit of room between ""not loving sub-...",[],test
...,...,...,...,...,...
16276,post,0x0f273c,We all do it sometimes don't worry.,[],test
16277,post,0xfc4c5d,This New Year I visited more relatives than us...,[],test
16278,post,0xb318a3,R u a dad or did ur dad leave u both have bad ...,[],test
16279,post,0x8f758e,I got my first raspberry from a crowd surfer f...,[],test
16280,post,0x3a9174,Pre-prepare direction plays hale and hearty si...,[],test

So, in this preprocessing step, I tried to load the training data and the test data into separate dataframe. The data that need to be separated are from final_posts.json, so I tried to load it first and then match the id with data_identification.csv and emotion .csv according to its split and take the emotions of each columns. The resulting dataframes are df_train_final and df_test

## 2. Feature Engineering Steps

### Label Encoding
Label encoding is used to convert the categorical data into a numerical format suitable for machine learning models (in this case distillbert and miniLM). In this case, emotion should be label encoded because without this, the model wouldn't be able to tell what's the emotion. I used a simple label encoder that was prepared by scikit-learn library

In [ ]:
# do a label encoding of the emotion so that distillbert and miniLM can recognize the emotion with numbers
label_encoder = LabelEncoder()
df_train_final['label'] = label_encoder.fit_transform(df_train_final['emotion'])

df_train_final

,root__type,id,root__source_post_text,root__source_post_hashtags,split,emotion,label
0,post,0x35663e,I bet there is an army of married couples who ...,[],train,joy,3
1,post,0xc78afe,This could only end badly.,[],train,fear,2
2,post,0x90089c,My sister squeezed a lime in her milk when she...,[],train,joy,3
3,post,0x2ffb63,Thank you so much❤️,[],train,joy,3
4,post,0x989146,Stinks because ive been in this program for a ...,[],train,joy,3
...,...,...,...,...,...,...,...
47885,post,0xd740f2,why is everybody seem sp serious?,[],train,joy,3
47886,post,0x99267e,"You can cross fuck off, its 10f all winter in ...",[],train,anger,0
47887,post,0x4afbe1,Guilty Gear actually did that before with Guil...,[],train,anger,0
47888,post,0xf5ba78,One of my favorite episodes.,[],train,joy,3
47889,post,0xb5a35a,Texans and Astros both shut out tonight. Houst...,"[texans, astros, sadness, losers]",train,sadness,4

### Train dataset tokenization

Tokenization is required for the input of distillbert and miniLM since they are transformer-based model, hence they need to tokenize the input to get the **context** of the words. This tokenization will produce input_ids and attention_mask. The input_id contains the full sequence of numerical tokens which represents the word in numbers, while attention_mask contains a 1 for every real token (including ``[CLS]`` and ``[SEP]``) and a 0 for every ``[PAD]`` token. ``[CLS]`` token is used to mark the starting point and ``[SEP]`` is used to mark the end of the sentences and also separating two segments (questions and answers). Finally, ``[PAD]`` token is used to fill the sequences if the sequence is shorter than the fixed maximum length of the determined sequence.

### FOR DISTILLBERT
Since I tried to use distillbert and minilm, I separate the tokenization because they are supposedly use the different tokenizer too

In [ ]:
### Add the code related to the feature engineering steps in cells inside this section
#This line initializes a tokenizer using the pre-trained DistilBERT model. "distilbert-base-uncased" specifies the model name, and "uncased" means the model is case-insensitive (it treats "Hello" and "hello" as the same).
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

#define tokenize function
def tokenize_function(word):
  return tokenizer(word, padding="max_length", truncation=True, max_length=128)

#apply the tokenize_function to the dataset
df_train_final['tokenized_output'] = df_train_final["root__source_post_text"].apply(tokenize_function)
df_train_final
# tokenized_dataset

,root__type,id,root__source_post_text,root__source_post_hashtags,split,emotion,label,tokenized_output
0,post,0x35663e,I bet there is an army of married couples who ...,[],train,joy,3,"[input_ids, attention_mask]"
1,post,0xc78afe,This could only end badly.,[],train,fear,2,"[input_ids, attention_mask]"
2,post,0x90089c,My sister squeezed a lime in her milk when she...,[],train,joy,3,"[input_ids, attention_mask]"
3,post,0x2ffb63,Thank you so much❤️,[],train,joy,3,"[input_ids, attention_mask]"
4,post,0x989146,Stinks because ive been in this program for a ...,[],train,joy,3,"[input_ids, attention_mask]"
...,...,...,...,...,...,...,...,...
47885,post,0xd740f2,why is everybody seem sp serious?,[],train,joy,3,"[input_ids, attention_mask]"
47886,post,0x99267e,"You can cross fuck off, its 10f all winter in ...",[],train,anger,0,"[input_ids, attention_mask]"
47887,post,0x4afbe1,Guilty Gear actually did that before with Guil...,[],train,anger,0,"[input_ids, attention_mask]"
47888,post,0xf5ba78,One of my favorite episodes.,[],train,joy,3,"[input_ids, attention_mask]"
47889,post,0xb5a35a,Texans and Astros both shut out tonight. Houst...,"[texans, astros, sadness, losers]",train,sadness,4,"[input_ids, attention_mask]"

### FOR MINILM

In [ ]:
### Add the code related to the feature engineering steps in cells inside this section

# Choose between L6 or L12, since the best result was produced by L12, I will use L12 here since it performs the best
# tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L12-v2")

#define tokenize function
def tokenize_function(word):
  return tokenizer(word, padding="max_length", truncation=True, max_length=128)

#apply the tokenize_function to the dataset
df_train_final['tokenized_output'] = df_train_final["root__source_post_text"].apply(tokenize_function)
df_train_final
# tokenized_dataset

### RUN FOR BOTH MODELS (Dataset Transform)

#### Train Dataset Transform

In [ ]:
# put the tokenization resilt inside new columns (input_ids and attention_mask)
input_ids = df_train_final['tokenized_output'].apply(lambda x: x['input_ids'])
attention_mask = df_train_final['tokenized_output'].apply(lambda x: x['attention_mask'])

df_train_final["input_ids"] = input_ids
df_train_final["attention_mask"] = attention_mask
# print(df_train_final)
# print(input_ids)
# print(attention_mask)

df_train_final

,root__type,id,root__source_post_text,root__source_post_hashtags,split,emotion,label,tokenized_output,input_ids,attention_mask
0,post,0x35663e,I bet there is an army of married couples who ...,[],train,joy,3,"[input_ids, attention_mask]","[101, 1045, 6655, 2045, 2003, 2019, 2390, 1997...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,post,0xc78afe,This could only end badly.,[],train,fear,2,"[input_ids, attention_mask]","[101, 2023, 2071, 2069, 2203, 6649, 1012, 102,...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
2,post,0x90089c,My sister squeezed a lime in her milk when she...,[],train,joy,3,"[input_ids, attention_mask]","[101, 2026, 2905, 7757, 1037, 14123, 1999, 201...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,post,0x2ffb63,Thank you so much❤️,[],train,joy,3,"[input_ids, attention_mask]","[101, 4067, 2017, 2061, 100, 102, 0, 0, 0, 0, ...","[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,post,0x989146,Stinks because ive been in this program for a ...,[],train,joy,3,"[input_ids, attention_mask]","[101, 27136, 2015, 2138, 4921, 2063, 2042, 199...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...,...,...,...,...,...,...,...
47885,post,0xd740f2,why is everybody seem sp serious?,[],train,joy,3,"[input_ids, attention_mask]","[101, 2339, 2003, 7955, 4025, 11867, 3809, 102...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, ..."
47886,post,0x99267e,"You can cross fuck off, its 10f all winter in ...",[],train,anger,0,"[input_ids, attention_mask]","[101, 2017, 2064, 2892, 6616, 2125, 1010, 2049...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
47887,post,0x4afbe1,Guilty Gear actually did that before with Guil...,[],train,anger,0,"[input_ids, attention_mask]","[101, 5905, 6718, 2941, 2106, 2008, 2077, 2007...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
47888,post,0xf5ba78,One of my favorite episodes.,[],train,joy,3,"[input_ids, attention_mask]","[101, 2028, 1997, 2026, 5440, 4178, 1012, 102,...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
47889,post,0xb5a35a,Texans and Astros both shut out tonight. Houst...,"[texans, astros, sadness, losers]",train,sadness,4,"[input_ids, attention_mask]","[101, 23246, 1998, 22058, 2119, 3844, 2041, 38...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

In [ ]:
# split the training data
X = df_train_final.drop('label', axis=1) # All columns EXCEPT the label
y = df_train_final['label']              # Only the label column

# Split into Training data to 80 percent and a combined Holdout for 20 percent, use stratify to make the separated data balance. 
# use random_state = 42 for consistent reproducability in separating data
X_train, X_holdout, y_train, y_holdout = train_test_split(
    X, 
    y, 
    test_size=0.2, 
    random_state=42, 
    stratify=y     
)

In [ ]:
# separate the validation and test data from the holdout
x_val, x_test, y_val, y_test  = train_test_split(X_holdout, y_holdout, test_size=0.5, random_state=42, stratify=y_holdout)
x_val

,root__type,id,root__source_post_text,root__source_post_hashtags,split,emotion,tokenized_output,input_ids,attention_mask
37890,post,0xafa8e1,You’re not being used but she has no right to ...,[],train,anger,"[input_ids, attention_mask]","[101, 2017, 1521, 2128, 2025, 2108, 2109, 2021...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
27845,post,0xa98e54,You sure showed him buddy.,[],train,joy,"[input_ids, attention_mask]","[101, 2017, 2469, 3662, 2032, 8937, 1012, 102,...","[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ..."
17874,post,0xa0869d,Keep pushing. You’ll come out of this stronger...,[],train,joy,"[input_ids, attention_mask]","[101, 2562, 6183, 1012, 2017, 1521, 2222, 2272...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
15070,post,0xc2f77d,"Oh, the ""Thomas the nuclear bomb""? That scarre...",[],train,fear,"[input_ids, attention_mask]","[101, 2821, 1010, 1996, 1000, 2726, 1996, 4517...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
47132,post,0xfe394a,Lmao we really tried that again,[],train,joy,"[input_ids, attention_mask]","[101, 1048, 2863, 2080, 2057, 2428, 2699, 2008...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...,...,...,...
17568,post,0x7a7139,"[NAME] damnit, have your upvote",[],train,anger,"[input_ids, attention_mask]","[101, 1031, 2171, 1033, 4365, 4183, 1010, 2031...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
12294,post,0xceb706,Great. Now some girl in Utah will appropriate ...,[],train,joy,"[input_ids, attention_mask]","[101, 2307, 1012, 2085, 2070, 2611, 1999, 6646...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
7044,post,0x3bc615,Now I can't wait to get my hands on all that w...,[],train,joy,"[input_ids, attention_mask]","[101, 2085, 1045, 2064, 1005, 1056, 3524, 2000...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
45114,post,0xfac91d,"LOL, once in a lifetime. Sheesh, this sub is o...",[],train,joy,"[input_ids, attention_mask]","[101, 8840, 2140, 1010, 2320, 1999, 1037, 6480...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4773,post,0x717a7e,Putting on head phones with a neutral song,[],train,joy,"[input_ids, attention_mask]","[101, 5128, 2006, 2132, 11640, 2007, 1037, 869...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, ..."

In [ ]:
# check the y_train
y_train

31193    4
35246    0
23687    0
33582    0
7355     3
        ..
37608    0
31392    3
3460     3
1307     5
19258    3
Name: label, Length: 38312, dtype: int32

In [ ]:
hugging_train = pd.concat([X_train, y_train], axis=1)
hugging_val = pd.concat([x_val, y_val], axis=1)
hugging_test = pd.concat([x_test, y_test], axis=1)

# put inside the dataloader that is used for hugging face ecosystem
train_dataset = Dataset.from_pandas(hugging_train[['input_ids', 'attention_mask', 'label']])
val_dataset = Dataset.from_pandas(hugging_val[['input_ids', 'attention_mask', 'label']])
test_dataset = Dataset.from_pandas(hugging_test[['input_ids', 'attention_mask', 'label']])

#### Test Dataset Transform (tokenization)

In [ ]:
# do the same steps above for the test dataset
tokenized_data = df_test['root__source_post_text'].apply(tokenize_function)

df_test['input_ids'] = tokenized_data.apply(lambda x: x['input_ids'])
df_test['attention_mask'] = tokenized_data.apply(lambda x: x['attention_mask'])

In [ ]:
df_predict = df_test[['input_ids', 'attention_mask']]
predict_dataset = Dataset.from_pandas(df_predict)

In [35]:
df_predict

,input_ids,attention_mask
0,"[101, 2057, 2288, 1996, 8086, 1010, 8209, 2256...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"[101, 1998, 2008, 2288, 2026, 2132, 3960, 1047...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
2,"[101, 2168, 1012, 5580, 2009, 1005, 1055, 2025...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, ..."
3,"[101, 2066, 2467, 1045, 2097, 3524, 1998, 2156...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,"[101, 2045, 1005, 1055, 1037, 2978, 1997, 2282...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...
16276,"[101, 2057, 2035, 2079, 2009, 2823, 2123, 1005...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, ..."
16277,"[101, 2023, 2047, 2095, 1045, 4716, 2062, 9064...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
16278,"[101, 1054, 1057, 1037, 3611, 2030, 2106, 2447...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
16279,"[101, 1045, 2288, 2026, 2034, 20710, 2361, 976...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
16280,"[101, 3653, 1011, 7374, 3257, 3248, 13084, 199...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."

## 3. Model Implementation Steps

### Metrics Function

In [ ]:
def compute_metrics(p):
    # p is an EvalPrediction object
    predictions = np.argmax(p.predictions, axis=1)
    
    # Calculate Macro F1 and Accuracy
    macro_f1 = f1_score(p.label_ids, predictions, average='macro')
    accuracy = accuracy_score(p.label_ids, predictions)
    precision = precision_score(p.label_ids, predictions, average='macro')
    recall = recall_score(p.label_ids, predictions, average='macro')
    
    return {
        'accuracy': accuracy,
        'precision_macro': precision,
        'recall_macro': recall,
        'f1_macro': macro_f1
    }

### Distillbert

In [ ]:
data_collator = DataCollatorWithPadding(tokenizer)
# Define the number of unique emotion categories
N = len(df_train_final.label.unique())
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=N 
)

training_args = TrainingArguments(
    output_dir='./results',              
    num_train_epochs=3,                  
    per_device_train_batch_size=16,      
    per_device_eval_batch_size=64,       
    warmup_steps=500,                    
    weight_decay=0.01,                  
    logging_dir='./logs',                
    logging_steps=100,
    eval_strategy="epoch",         # Evaluate the model at the end of each epoch
    save_strategy="epoch",               # Save a checkpoint at the end of each epoch
    load_best_model_at_end=True,         # Load the best model found during training based on validation loss
)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Since I did not install pytorch + cuda and run it with GPU, I run this code in Google Colab and load the model below. (please ignore the error since I did not want to run the code for 6 hours using CPU and did not want to install pytorch+cuda since it takes so much space in my laptop). But you can try to run and this code will not have any problem

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# Start the training and fine-tuning process
trainer.train()

d:\Data Mining\DM2025-Lab2-Exercise\.venv\Lib\site-packages\torch\utils\data\dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

KeyboardInterrupt:

The metrics that I got for this run can be seen below:

![distillbert](./pics/distillbert_metrics.png)

### MiniLM-L6-v2

In [ ]:
from transformers import TrainingArguments
from transformers import AutoModelForSequenceClassification
from transformers import DataCollatorWithPadding
from transformers import EarlyStoppingCallback

data_collator = DataCollatorWithPadding(tokenizer)
# Define the number of unique emotion categories
N = len(df_train_final.label.unique())
model = AutoModelForSequenceClassification.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2",
    num_labels=N
)

training_args = TrainingArguments(
    output_dir='./results',              
    num_train_epochs=10,                  
    per_device_train_batch_size=16,      
    per_device_eval_batch_size=64,       
    warmup_steps=500,                    
    weight_decay=0.02,                   
    logging_dir='./logs',                
    logging_steps=100,
    learning_rate = 2e-5,
    eval_strategy="epoch",         # Evaluate the model at the end of each epoch
    save_strategy="epoch",               # Save a checkpoint at the end of each epoch
    load_best_model_at_end=True,         # Load the best model found during training based on validation loss
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=3, # Stop after 3 epochs without improvement
            early_stopping_threshold=0.001 # Minimum change required to count as improvement
        )
    ]
)

# Start the training and fine-tuning process
trainer.train()

The metrics that I got from this model can be seen below:

![MiniLM-L6](./pics/mini_LM6_metrics_result.png)

### MiniLM-L12-v2

In [ ]:
from transformers import TrainingArguments
from transformers import AutoModelForSequenceClassification
from transformers import DataCollatorWithPadding
from transformers import EarlyStoppingCallback

data_collator = DataCollatorWithPadding(tokenizer)
# Define the number of unique emotion categories
N = len(df_train_final.label.unique())
model = AutoModelForSequenceClassification.from_pretrained(
    "sentence-transformers/all-MiniLM-L12-v2",
    num_labels=N
)

training_args = TrainingArguments(
    output_dir='./results',              # Directory to save checkpoints and results
    num_train_epochs=10,                  # Number of training epochs (3 is a good starting point for BERT models)
    per_device_train_batch_size=16,      # Batch size per GPU/CPU for training
    per_device_eval_batch_size=64,       # Batch size for evaluation (can be larger)
    warmup_steps=500,                    # Number of warm-up steps for learning rate scheduler
    weight_decay=0.05,                   # Strength of weight decay (L2 regularization)
    logging_dir='./logs',                # Directory for storing logs
    logging_steps=100,
    learning_rate = 2e-5,
    eval_strategy="epoch",         # Evaluate the model at the end of each epoch
    save_strategy="epoch",               # Save a checkpoint at the end of each epoch
    load_best_model_at_end=True,         # Load the best model found during training based on validation loss
)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=3, # Stop after 3 epochs without improvement
            early_stopping_threshold=0.001 # Minimum change required to count as improvement
        )
    ]
)

# Start the training and fine-tuning process
trainer.train()

The metrics that I got with this model can be seen below:

![Mini LM](./pics/mini_LM_metrics_result.png)

### Test using new unseen test dataset

In [ ]:
metrics_on_test_set = trainer.predict(test_dataset)

In [ ]:
metrics_on_test_set

### Save Model

In [ ]:
# specify the output of the save/load function

# for miniLM
output_directory = "./mini_lm_fine_tune"

# for distillbert
# output_directory = "./Best_model_distillbert"

In [ ]:
trainer.save_model(output_directory)
tokenizer.save_pretrained(output_directory)

print(f"Model and tokenizer saved successfully to: {output_directory}")

### Load Model

In [ ]:
loaded_tokenizer = AutoTokenizer.from_pretrained(output_directory)
loaded_model = AutoModelForSequenceClassification.from_pretrained(output_directory)

### Inference
to output the predictions

In [ ]:
predictor = Trainer(
    model=model,
    data_collator=DataCollatorWithPadding(tokenizer)
)

raw_predictions = predictor.predict(predict_dataset)

In [ ]:
predicted_indices = np.argmax(raw_predictions.predictions, axis=1)
final_emotions = label_encoder.inverse_transform(predicted_indices)

df_test['emotion'] = final_emotions

print(df_test[['id', 'emotion']].head())

In [ ]:
df_test.to_csv('predicted.csv', columns=['id', 'emotion'], index=False)

## Model Explanation

### DistillBERT
I decide to use DistillBERT because it is a distilled model that retrain the capabilities of the the original BERT model with far more fewer parameters and sacrificing a little bit of the capabilities. DistillBERT itself is a model that was found by Google in 2019 that was made with Knowledge distillation which the model tries to learn from the teacher model, in this case BERT to reproduce the behaviour of the teacher model in a more compact size. So, this model has the same architecture as BERT which can be seen below:

![Distill Bert](./pics/BERT_Architecture.png)

So what is this? This is the model architecture of BERT that is based on a multi-layer bidirectional Transformer encoder. But first of all, in order for BERT to understand the input, Tokenization should be done for the inputs which I already explained above. Then training will be started by masking some of the words so that the model will learn on how to fill and predict that masked word. But that's not all, it was also trained on a question answering task with next-sentence prediction task to make the model understands the relationship of the sentences. In this case, BERT would be a good choice for predicting the emotion of the input text because this model is trained specifically for diverse natural language understanding tasks, including text classification. Because we need to predict the emotion from the text, I can use this model without having to train the model from start, and just fine tune it with small number of epochs and optimal hyperparameters for the model to predict the emotions. Then we have a distillbert which  has the same general architecture as BERT, but the token-type embeddings and the pooler are removed while the number of layers is reduced by half making it a much smaller model. Since the input of the text is mostly short, I also decide to use this model and it turns out being able to produce decent results of 0.6630 in the public leaderboard.

Source:
Devlin, J., Chang, M. W., Lee, K., & Toutanova, K. (2019, June). Bert: Pre-training of deep bidirectional transformers for language understanding. In Proceedings of the 2019 conference of the North American chapter of the association for computational linguistics: human language technologies, volume 1 (long and short papers) (pp. 4171-4186).
Sanh, V., Debut, L., Chaumond, J., & Wolf, T. (2019). DistilBERT, a distilled version of BERT: smaller, faster, cheaper and lighter. arXiv preprint arXiv:1910.01108.

## MiniLM
MiniLM is also a distilled model found in 2020 based on the transfomer model which was trained with a teacher model transferring its knowledge to the student model by mimicing its self-attention module instead of making each Transformer layer of the student is required to have the same architecture as its teacher like in DistillBERT. In the MiniLM paper, they did specify BERT and XLM-R language model that were used as the teacher model, and since I tried to use the V2, it turns out that this model was distilled from BERT, RoBERTa, and XLM-R models. So, why does this model might achieve a better result compared to DistillBERT? It's because MiniLM transfered the knowledge of the attention head which is the most important component in transformer and it does not sacrifice half of the teacher model layers making it still retains the full knowledge of the original full layers. Moreover, from the paper, it almost beats all of the metrics compared to DistillBERT and TinyBERT. This model manages to score 0.6810 in the public leaderboard of the competition.

![MiniLM Architecture](./pics/mini_LM_architecture.png)

Source:
Wang, W., Wei, F., Dong, L., Bao, H., Yang, N., & Zhou, M. (2020). Minilm: Deep self-attention distillation for task-agnostic compression of pre-trained transformers. Advances in neural information processing systems, 33, 5776-5788.

## Conclusion of the model

MiniLM-L12-V2, a distilled model based on BERT, RoBERTa, and XLM-R models manage to perform the best with a score of 0.6810 in the public leaderboard while DistillBERT which supposedly able to perform well only manages to score 0.6630.

# Bonus Section

## Different things that I tried

So at first, I tried to use the base BERT base uncased because most of the papers and experiments used this. But, it turns out that in the training process, it has a bad F1 score and so I decided to use DistillBERT because it is a less complex model and the fact that we only have 47890 data for training. I'm afraid that since BERT is a large model, fine tune it with small amount of data got overwhelmed with the prelearned knowledge making the model overfit and made it perform worse. So I decide to use DistillBERT and it manages to score 0.6630. Then, I searched for a better model and found MiniLM which has different approach in distilling the larger model. At first I tried to use MiniLM-L6-V2 which means that the model has 6 transformer layers precisely half of the original BERT's transformer layers hence making it has the same amount of layers in DistillBERT. But, it turns out that it can only score 0.6615 in the public leaderboard. So, I tried to fine tune it with lower learning rate and it manages to score 0.6677. Because this model manages to do a better job thatn DistillBERT, I believe that this model might perform better using the similar setup from the paper, so I tried to use MiniLM-L12-V2 that has the same transformer layers as the larger model that it was based on. Hence, my hypothesis was correct, it manages to score 0.6810. Finally, I tried the last model named RobertA. RoBERTa is a more robust trained BERT model with more data and large batches and supposedly able to perform better than BERT. But when I compared the F1 score on the training with MiniLM, it actually produces lower score, so I decided not to experiment more with this model. Moreover, I already thought that it won't have work better because BERT, which can be considered as a similar model with size of RobertA, also can't perform well. Here are the score on the public leaderboard of my attempts:

![Score Attempts](./pics/attempts.png)

In conclusion, after I tried BERT, DistillBert, MiniLM-L6-V2, MiniLM-L12-V2, and RobertA, it turns out that MiniLM-L12-V2 manage to perform the best of them all.

## Insights that I gained

In order to select a model that is suitable for certain task, we can't just always select the most popular and powerful model. We need to see the data and determine which model might be suitable for it. For example, since the input of the data given for this homework are short sentences and only 47890 data was prepared, a more compact, but powerful model would be able to produce the best results. Lastly, choosing the best hyperparameter also contributes to the best performance of the model.